# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DigitalGenerationKOKKURI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DigitalGenerationKOKKURI

  # Util
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'SwiftDate'
  pod 'SwiftyUserDefaults'

  # Rx
  pod 'RxSwift'
  pod 'RxRealm'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'RxGesture'

  pod 'SVProgressHUD'

end
